### ISSUE TITLE
Got error while parsing JS file using https://www.npmjs.com/package/angular-gettext-cli

### ISSUE THREAD

**Issue by airs0urce** [rubenv/angular-gettext-tools#157]
/usr/local/lib/node_modules/angular-gettext-cli/node_modules/angular-gettext-tools/lib/extract.js:54
    if (node.type === 'Literal') {
            ^

TypeError: Cannot read property 'type' of undefined
    at getJSExpression (/usr/local/lib/node_modules/angular-gettext-cli/node_modules/angular-gettext-tools/lib/extract.js:54:13)
    at /usr/local/lib/node_modules/angular-gettext-cli/node_modules/angular-gettext-tools/lib/extract.js:267:28
    at walkJs (/usr/local/lib/node_modules/angular-gettext-cli/node_modules/angular-gettext-tools/lib/extract.js:39:5)

**Comment by airs0urce** [comment]
Actually I had wrong syntax for getPlural()
